import measured from './measuredMapping.json';
import { ccToEnumIndex, ccToReal } from '../midi/scaling';
import { CHAIN_ORDER_BLOCK_IDS } from '../midi/sysex';
import { activeParams, findBlock } from '../store/patchDefaults';
import type { ServerEffect } from '../midi/bridgeTransport';

/**
 * Translation of the pedal's runtime snapshot (`live.effects`) into the editor's patch model,
 * driven by the table measured on a real pedal (measuredMapping.json, generated by
 * scripts/build_mapping.py from scripts/calibrate_mapping.py runs). To update it, regenerate
 * the JSON; nothing else here is hard-coded.
 */

interface MeasuredType {
  name: string;
  variant: number;
  param_count: number;
  params: { index: number; cc: number | null }[];
}

const blocks = measured.blocks as unknown as Record<string, { types: Record<string, MeasuredType> }>;

/** Snapshot entry i is this block. Note that del comes before mod. */
export const RUNTIME_BLOCK_ORDER: readonly string[] = measured.runtime_blocks;

/** Amp and cab have one entry ("*") for every model. */
export function measuredType(blockId: string, typeId: number): MeasuredType | null {
  const types = blocks[blockId]?.types;
  if (!types) return null;
  return types[String(typeId)] ?? types['*'] ?? null;
}

/** Editor type id whose measured variant equals the reported one. Amp and cab are not typed this way. */
export function typeIdForVariant(blockId: string, variant: number): number | null {
  if (blocks[blockId]?.types['*']) return null;
  const hit = findBlock(blockId).types.find((t) => measuredType(blockId, t.id)?.variant === variant);
  return hit?.id ?? null;
}

/** Ids of the editor controls that exist in the snapshot for this block and type. */
export function readableParamIds(blockId: string, typeId: number): Set<string> {
  const m = measuredType(blockId, typeId);
  const ccs = new Set((m?.params ?? []).map((p) => p.cc).filter((cc): cc is number => cc !== null));
  return new Set(activeParams(findBlock(blockId), typeId).filter((s) => ccs.has(s.cc)).map((s) => s.id));
}

export interface RemoteBlock {
  on?: boolean;
  /** Absent when the type cannot be told from the snapshot. */
  typeId?: number;
  /** Real-world values by parameter id, only for controls that can be read back. */
  params?: Record<string, number>;
}

export interface RemoteSnapshot {
  blocks: Record<string, RemoteBlock>;
  /** Block ids whose layout does not match the measured table (other firmware). */
  unaligned: string[];
  chainOrder: string[] | null;
}

export function translateEffect(blockId: string, effect: ServerEffect): RemoteBlock & { aligned: boolean } {
  const block = findBlock(blockId);
  const fixedModel = blocks[blockId]?.types['*'] !== undefined;
  const typeId = fixedModel ? undefined : (typeIdForVariant(blockId, effect.variant) ?? undefined);
  const base = { on: effect.enabled };
  if (!fixedModel && typeId === undefined) return { ...base, aligned: false };

  const m = measuredType(blockId, typeId ?? 0);
  if (!m || effect.params.length !== m.param_count) return { ...base, typeId, aligned: false };

  const specs = activeParams(block, typeId ?? 0);
  const params: Record<string, number> = {};
  for (const { index, cc } of m.params) {
    if (cc === null) continue;
    const spec = specs.find((s) => s.cc === cc);
    const norm = effect.params[index];
    if (!spec || typeof norm !== 'number') continue;
    const cc127 = Math.round(Math.min(1, Math.max(0, norm)) * 127);
    params[spec.id] = spec.kind === 'enum' ? ccToEnumIndex(cc127, spec.options.length) : ccToReal(spec.min, spec.max, cc127);
  }
  return { ...base, typeId, params, aligned: true };
}

export function translateEffects(effects: ServerEffect[], chainOrder: string[] | null = null): RemoteSnapshot {
  const out: Record<string, RemoteBlock> = {};
  const unaligned: string[] = [];
  effects.forEach((effect, position) => {
    const blockId = RUNTIME_BLOCK_ORDER[Number.isInteger(effect.index) ? effect.index : position];
    if (!blockId) return;
    const { aligned, ...rest } = translateEffect(blockId, effect);
    out[blockId] = rest;
    if (!aligned) unaligned.push(blockId);
  });
  return { blocks: out, unaligned, chainOrder };
}

export function blockIdsToChainOrder(ids: string[]): number[] {
  return ids.map((id) => CHAIN_ORDER_BLOCK_IDS[id]);
}
